export const ADJECTIVES: readonly string[] = Object.freeze([
  "red", "blue", "green", "amber", "bright", "calm", "quick", "brave", "clever", "cosy",
  "crisp", "deep", "eager", "early", "fair", "fancy", "fast", "fierce", "fluffy", "fresh",
  "funny", "gentle", "giant", "golden", "grand", "great", "happy", "hidden", "humble", "icy",
  "jolly", "kind", "late", "lazy", "light", "loud", "lucky", "lush", "merry", "misty",
  "mossy", "noble", "odd", "old", "open", "pale", "plain", "plush", "polite", "proud",
  "quiet", "rapid", "rare", "raw", "ripe", "rough", "round", "royal", "rustic", "salty",
  "shiny", "short", "shy", "silent", "silky", "silver", "simple", "sleek", "slick", "slow",
  "small", "smart", "smooth", "snowy", "soft", "solid", "sour", "sparse", "spicy", "spry",
  "stark", "steady", "steep", "stern", "still", "stony", "stormy", "strong", "sunny", "sweet",
  "swift", "tall", "tame", "tangy", "tart", "tender", "thick", "thin", "tidy", "tiny",
  "tired", "tough", "tricky", "true", "twin", "vague", "vast", "vital", "vivid", "warm",
  "wary", "wavy", "weak", "wet", "white", "wild", "windy", "wise", "witty", "woolly",
  "young", "zany", "zesty", "able", "active", "agile", "airy", "alert", "alive", "ample",
  "arid", "ashy", "awake", "balmy", "basic", "beige", "bold", "bony", "bouncy", "bushy",
  "busy", "caring", "cheery", "chewy", "chilly", "chirpy", "chubby", "chunky", "classy", "clean",
  "clear", "cloudy", "comfy", "cool", "coy", "crafty", "creamy", "curly", "curvy", "daily",
  "damp", "dandy", "dapper", "dappled", "dark", "dashing", "dewy", "dry", "dusty", "dutch",
  "easy", "empty", "even", "fabled", "faint", "famed", "feisty", "firm", "flat", "flinty",
  "fluent", "foamy", "foggy", "fond", "formal", "free", "frisky", "frosty", "full", "furry",
  "fuzzy", "giddy", "glad", "glossy", "grainy", "grassy", "hardy", "hasty", "hearty", "honest",
]);
