export const NOUNS: readonly string[] = Object.freeze([
  "flower", "river", "moon", "star", "cloud", "forest", "stone", "leaf", "wave", "hill",
  "valley", "meadow", "creek", "brook", "peak", "cliff", "ridge", "shore", "bay", "cove",
  "harbor", "island", "pond", "lake", "ocean", "desert", "canyon", "cavern", "tunnel", "bridge",
  "garden", "orchard", "vine", "root", "seed", "bloom", "petal", "fern", "moss", "reed",
  "acorn", "cedar", "birch", "maple", "oak", "pine", "ash", "fig", "plum", "peach",
  "apple", "berry", "grape", "lemon", "lime", "mango", "melon", "olive", "pear", "mint",
  "sage", "thyme", "clove", "chili", "sugar", "honey", "cocoa", "bread", "cream", "milk",
  "cheese", "butter", "cookie", "muffin", "noodle", "omelet", "pepper", "salad", "scone", "waffle",
  "lynx", "otter", "badger", "beaver", "bison", "cat", "deer", "dog", "eagle", "falcon",
  "ferret", "finch", "fox", "frog", "goat", "goose", "gull", "hare", "hawk", "hedgehog",
  "heron", "horse", "lamb", "lark", "lion", "llama", "mole", "moose", "mouse", "newt",
  "owl", "panda", "parrot", "pigeon", "rabbit", "raven", "robin", "salmon", "seal", "shark",
  "sheep", "shrew", "skunk", "sloth", "snail", "sparrow", "spider", "squid", "stag", "stork",
  "swan", "tiger", "toad", "trout", "turtle", "vulture", "wolf", "zebra", "anchor", "arrow",
  "basket", "beacon", "bell", "book", "bottle", "bowl", "candle", "carpet", "chair", "clock",
  "compass", "crown", "cup", "drum", "engine", "fabric", "feather", "fiddle", "flag", "flask",
  "flute", "gadget", "glass", "globe", "hammer", "hat", "helmet", "horn", "hose", "kettle",
  "key", "kite", "lamp", "lantern", "lens", "letter", "lock", "lute", "mask", "mirror",
  "oar", "orb", "pail", "palette", "parcel", "pen", "pencil", "pillow", "pipe", "pocket",
  "quilt", "ribbon", "rug", "scarf", "shield", "ship", "sketch", "statue", "sword", "token",
]);
